### ISSUE TITLE
YouTube API setup?

### ISSUE THREAD

**Issue by MattBDev** [wasteam/waslibs#22]
It is a bit confusing on what to do to get an API token for YouTube when making a Windows App. Instructions on how to do so would be nice.

**Comment by javitosanchez** [comment]
In order to create a new YT api key you have to go [here](https://console.developers.google.com/iam-admin/projects). Instructions of how to create it are [here](https://blogs.msdn.microsoft.com/windows_app_studio_news/2015/02/23/how-to-add-a-youtube-datasource-in-windows-appstudio/). Start reading from point 4.
