### ISSUE TITLE
http://appstudio.windows.com 1.4.4 feedback

### ISSUE THREAD

**Issue by k0st1x** [wasteam/waslibs#30]
1. crash on opening menu (...) on detail page "SectionXXXDetailPage.xaml" (only in win10mobile):
there is a Windows.UI.Xaml.LayoutCycleException with "Layout cycle detected.  Layout could not complete" message.
But if i remove AppBarButtons from <was_actions:ActionsCommandBar.SecondaryCommands> so application will work without issues/crashes.

Can I remove this buttons from the Web UI? Or I should update sources and recompile its locally?

2. section icons become b/w gray-scaled (by the transparency mask), but on the website I have uploaded its colored. May I revert to previous behavior?

3. Detail page "SectionXXXDetailPage.xaml" showes HTML Content without images (as text tags (<img .../> or <br/>), but previously its were displayed without issues.
:( can it be reverted to previous behavior?
Or maybe just remove all tags :) 

4. overall performance is greatly improved. thank you for your great job!

**Comment by ralarcon** [comment]
Hi, 

We will review in detail this issues as soon as possible. Can you share your your "Project Id" by sending it to appstudiosupport@outlook.com in order to have a closer look to your issues (you can pick it from the Project url while editing your project and should be something similar to: http://appstudio.windows.com/projects/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX/content)?. 

Regarding the AppBarButtons, those become from the "Page Actions" that you can see while editing a section in the "Detail Page" configuration. Some of these  "Page Actions" can be deleted but other are added by default and can't be removed. So, in those cases, you will need to edit the source code.

Finally, if you are downloading the source code, you can point to the v1.4.3 by changing it in the project.json file (or thru "Manage NuGet References for this project" in the Solution Explorer). 

Anyway, we will get you informed.

Best Regards.

**Comment by javitosanchez** [comment]
We are reviewing your issues; 
1. We cannot reproduce this crash. Could you tell us which version of Windows Mobile do you have? (Settings > system > about), and the steps to reproduce it?
2. We are reviewing the problem with the color conversion in the Nav pane. We'll keep you updated
3. The problem is the content is not real html. Is plain text mixed with html and the HtmlBlock control renders it as plain text. I just created an issue for this #31.

**Comment by k0st1x** [comment]
1. OS Version - 10.0.10586.318 ("Insider Release Preview" Ring)
> the steps to reproduce it?
I can reproduce its only on my project in appstudio.windows.com, I've send "Project Id" by email to appstudiosupport@outlook.com

I will check later this issue on "Insider Fast" Ring

**Comment by k0st1x** [comment]
Just tested on 10.0.10586.420 from the "insider Fast" ring and issue is reproduced

**Comment by k0st1x** [comment]
Just tested on the emulator 10.0.10586.0 and its works fine.
But this information is not helping me to debug this issue : (

**Comment by javitosanchez** [comment]
We cannot reproduce it in none of the devices we have (tried with different os versions). Could you send us the call stack by [appstudiosupport@outlook.com](appstudiosupport@outlook.com)?

**Comment by k0st1x** [comment]
Unfortunately there is no 'call stack',
I've disabled "just my code" option in the VS, enabled all exception types,
but breakpoint only raises in the App.UnhandledException event handler.
Exception has no stacktrace or any link to issued visual element,
here is how I get exception: https://yadi.sk/i/1ULKpj5xsYuPK
and here is what the exception.Data contains https://yadi.sk/i/yCYuOUQHsYuSz

Also I test project on the Lumia950 (with the same OS version 10.0.10586.420) and it works without errors.
So the issue is specific for my device only, sometime i will change device :)

Please give me a comment only about the issue with b/w icons in the hamburger menu. Am I clear described issue? can i give more useful information? Is issue reproduced? Is it issue or feature?

**Comment by k0st1x** [comment]
@javitosanchez is there any updates on issue with b/w-shell-icons?

**Comment by javitosanchez** [comment]
@k0st1x it should be solved now. Can you try?

**Comment by k0st1x** [comment]
Just checked project generation on the web site. and its working perfectly.
issue with icons is fixed.
Many thanks.
