### ISSUE TITLE
ShellControl NavigationItem Position

### ISSUE THREAD

**Issue by mashabek** [wasteam/waslibs#47]
Hi! I found that is unable to set NavigationItem position in ShellControl. How can I go around this problem? 
I want something like this
![sketch](https://cloud.githubusercontent.com/assets/17130500/18271259/a5577a0a-744a-11e6-9e60-f2386dcb0a15.png)

**Comment by javitosanchez** [comment]
The current implementation of the [ShellControl](https://github.com/wasteam/waslibs/tree/master/src/AppStudio.Uwp/Controls/ShellControl) doesn't support anchoring navigation items to bottom. What you can do in order to group the items visually is insert "separators" between them:

`NavigationItems.Add(NavigationItem.Separator)`

**Comment by mashabek** [comment]
Thank u for feedback! I think it will available soon!
